server:
  port: 80
  path: /messages
  interval: 60000

database:
  username: root
  password: xA123456
  database: p2m_message_server
  host: mysql
  dialect: mysql

jpush:
  appKey:
  masterSecret:
